version: "3.8"

services:
  db: 
    image: postgres
    container_name: localdb
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      .env
    volumes:
      - local_dbdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_dbdata:
  pgadmin-data:

  
  